micronaut:
  application:
    name: kotlin-micronaut
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/test
    driverClassName: org.postgresql.Driver
    username: hello
    password: world
    schema-generate: CREATE_DROP
    dialect: POSTGRES

redis:
  uri: redis://localhost

